blox:
  world_map:
    pose: [0, 0, 0, 1, 0, 0, 0]
    "integrator_type": "occupancy"

cuboid:
  floor:
    dims: [1.5, 1.5, 0.05] # x, y, z
    pose: [0.9, 0.0, 0.04, 1, 0, 0, 0.0] # x, y, z, qw, qx, qy, qz

  wheelchair:
    dims: [0.1, 0.5, 0.5] # x, y, z
    pose: [-0.4, -0.25, 0.25, 0.9914, 0.0, -0.1305, 0.0] # x, y, z, qw, qx, qy, qz